chore: switch to sapphire
skyra-project/alestra pull request #389
Opened 2020-10-28 22:06 UTC by kyranet

2020-10-28 22:11 UTC, Favna commented on src/Alestra.ts
> -	client.console.error(error);
```
client.token = TOKEN

client.connect()
```

This was still the dumbest and ao-est decision of Klasa Core ever if you ask me. Thank god we don't have that anymore.

2020-10-28 22:15 UTC, Favna requested changes

2020-10-28 22:15 UTC, Favna commented on src/commands/Admin/exec.ts
> +	description: 'COMMAND_EXEC_DESCRIPTION',
Replace this with an actual description please. I know it doesn't mean much but this is just ugly.

2020-10-28 22:15 UTC, Favna commented on src/commands/Admin/update.ts
> +		if (args.getFlags('fullRebuild')) await this.cleanDist(message);
```suggestion
		if (args.getFlags('clean')) await this.cleanDist(message);
```

Lets match Skyra's flags

2020-10-29 00:30 UTC, kyranet commented
With ca1cf8d, the banner looks like this:

![image](https://user-images.githubusercontent.com/24852502/97510990-47739000-1986-11eb-8747-cefbf20decd1.png)

2020-10-29 00:39 UTC, kyranet commented
Screenshots from VSCode (with a small enhancement).

## Production mode:
![image](https://user-images.githubusercontent.com/24852502/97511525-90781400-1987-11eb-808a-36484a3c6b50.png)

## Development mode:
![image](https://user-images.githubusercontent.com/24852502/97511534-940b9b00-1987-11eb-852c-48c792ba0a78.png)

2020-10-29 07:45 UTC, Favna approved these changes

2020-10-29 08:31 UTC, merged